In [1]:
# importing libraires 
import numpy as np
import pandas as pd 
import os 
import tensorflow as tf 
import librosa as lb 
import matplotlib.pyplot as plt


from tensorflow.keras.utils import to_categorical 
from tensorflow.keras import Sequential , layers 

from sklearn.model_selection import train_test_split 
from sklearn.metrics import confusion_matrix , classification_report 
import IPython.display as ipd

# 2) Modelimizi oluşturalım

In [27]:
model = Sequential([
    layers.Dense(800 , activation = 'relu' , input_shape = (128 , )),
    layers.Dense(400 , activation = 'relu'),
    layers.Dense(200 , activation = 'relu'),
    layers.Dense(100 , activation = 'relu'),
    layers.Dense(50 , activation = 'relu'),
    layers.Dense(10 , activation = 'softmax') # Çıkış 10 Düğüm Çünkü 10 kategori var
])

In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 800)               103200    
                                                                 
 dense_1 (Dense)             (None, 400)               320400    
                                                                 
 dense_2 (Dense)             (None, 200)               80200     
                                                                 
 dense_3 (Dense)             (None, 100)               20100     
                                                                 
 dense_4 (Dense)             (None, 50)                5050      
                                                                 
 dense_5 (Dense)             (None, 10)                510       
                                                                 
Total params: 529,460
Trainable params: 529,460
Non-trai

In [29]:
model.compile(loss = 'categorical_crossentropy' ,#(loss) fonksiyonu olarak “categorical_crossentropy” kullanılmıştır. Temelde “categorical_crossentropy” iki olasılık dağılımı arasındaki mesafeyi ölçer.
              optimizer = 'adam' ,
              metrics = ['accuracy'])

# 3) Oluşturduğumuz modeli eğitelim.

In [30]:
from datetime import datetime
start = datetime.now()
history = model.fit(X_train , y_train , epochs = 30)
duration = datetime.now() - start
print("Training completed in time: ", duration)

Epoch 1/30
219/219 [==============================] - 6s 8ms/step - loss: 1.7342 - accuracy: 0.4460
Epoch 2/30
219/219 [==============================] - 1s 7ms/step - loss: 1.0318 - accuracy: 0.6568
Epoch 3/30
219/219 [==============================] - 2s 7ms/step - loss: 0.7630 - accuracy: 0.7469
Epoch 4/30
219/219 [==============================] - 2s 8ms/step - loss: 0.5924 - accuracy: 0.8062
Epoch 5/30
219/219 [==============================] - 2s 7ms/step - loss: 0.4628 - accuracy: 0.8518
Epoch 6/30
219/219 [==============================] - 2s 7ms/step - loss: 0.3668 - accuracy: 0.8750
Epoch 7/30
219/219 [==============================] - 2s 7ms/step - loss: 0.3322 - accuracy: 0.8893
Epoch 8/30
219/219 [==============================] - 2s 7ms/step - loss: 0.2695 - accuracy: 0.9085
Epoch 9/30
219/219 [==============================] - 2s 7ms/step - loss: 0.2405 - accuracy: 0.9175
Epoch 10/30
219/219 [==============================] - 2s 7ms/step - loss: 0.2153 - accuracy: 0.9251

# Modelin başarısına bakalım.

In [31]:
test_accuracy=model.evaluate(X_test,y_test,verbose=0)
print(test_accuracy[1])

0.9158557653427124


In [32]:
y_true = np.argmax(y_test , axis = 1)
y_pred = np.argmax(model.predict(X_test) , axis = 1)

print(confusion_matrix(y_true , y_pred))

55/55 [==============================] - 0s 3ms/step
[[191   0   3   0   0   6   2   1   0   0]
 [  1  76   3   0   0   1   0   2   0   3]
 [  1   0 172   1   0   0   4   0   2   3]
 [  1   2   8 174   0   4   7   1   4   0]
 [  1   0   3  10 182   2   2   3   0   3]
 [  0   0   3   1   0 189   0   0   0   0]
 [  1   0   1   3   0   0  66   0   0   1]
 [  0   0   3   1   6   1   0 197   0   0]
 [  1   0   2   1   0   0   0   0 161   0]
 [  0   1  18   9   1   2   2   0   5 192]]


In [33]:
y_test.shape

(1747, 10)

In [34]:
class_names = data.groupby('classID')['class']
class_names.unique()

classID
0     [air_conditioner]
1            [car_horn]
2    [children_playing]
3            [dog_bark]
4            [drilling]
5       [engine_idling]
6            [gun_shot]
7          [jackhammer]
8               [siren]
9        [street_music]
Name: class, dtype: object

In [35]:
class_names = pd.DataFrame(class_names.unique() )
class_names

class
classID                    
0         [air_conditioner]
1                [car_horn]
2        [children_playing]
3                [dog_bark]
4                [drilling]
5           [engine_idling]
6                [gun_shot]
7              [jackhammer]
8                   [siren]
9            [street_music]

**Herhangi bir sesdosyası ile modelimizi test edelim.**

In [36]:
test_accuracy=model.evaluate(X_test,y_test,verbose=0)
print(test_accuracy[1])

0.9158557653427124


In [37]:
test_path = 'UrbanSound8K/audio/fold9/204067-2-0-32.wav'
feature = np.array([feature_extract(test_path)])
ID = np.argmax(model.predict(feature)[0])
print(ID)
print(class_names.loc[ID , 'class'])
ipd.Audio(test_path)

1/1 [==============================] - 0s 46ms/step
2
['children_playing']
